= Configuring
:doctype: book
:sectnums:
:toc: left
:icons: font
:experimental:
:sourcedir: .

You must fine-tune Memory and Database settings for better performance before using {this-platform} {this-application} in production.
Once you complete setting up the Gateway you must configure the SS7 Stack and GMLC paramters. {this-platform} {this-application} comes with a convenient user-friendly Graphical User Interface (GUI) and a Command Line Interface (CLI) that will allow you to configure, monitor and manage the Gateway.
While the CLI tool allows complete configuration and control of the Gateway, the GUI-based management enhances the usability of the Gateway and gives you the ability to configure and manage the GMLC Gateway dynamically.
This chapter will explain how to manage the Gateway effectively using both the GUI and the CLI. 

== Memory Settings

You should fine tune the JVM memory settings based on your needs but we recommend you allocate a minimum of 3 GB for initial and maximum heap size.
These settings are specified in the file[path]_{this-folder}-gmlc-/jboss-5.1.0.GA/bin/run.conf_. 

-Xms3072m::
  Initial heap size, set in megabytes

-Xmx3072m::
  Maximum heap size, set in megabytes

[[_java_setting]]
== JSupported Java Version

GMLC Gateway can run only with Java 7 JRE or JDK.
We refered Oracle Java 7 JDK. 

[[_http_client_ra]]
== Configuring JSLEE http-client RA

{this-platform} {this-application} acts as a HTTP Client to achieve GMLC pull by sending a HTTP POST/GET request to GMLC gateway.
You must configure the HTTP Client JSLEE Resource Adaptor's properties to suit your requirements.
Please refer to the SLEE RA HTTP Client User Guide available in [path]_{this-folder}-gmlc-/docs/slee/RestComm_SLEE_RA_HTTP_Client_User_Guide.pdf_. 

[[_configuring_ss7]]
== Configuring the SS7 Stack

You must configure the SS7 Stack prior to configuring GMLC.
For details on configuring the SS7 Stack please refer to the RestComm SS7 Stack User Guide.
The RestComm SS7 Stack User Guide lists all available Shell commands and GUI operations to configure SS7.
In addition, help files are also available for every Shell command providing all details relevant to the command. 
